import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { analyzeProject } from '@lmv/migration-core';
const root = new URL('../packages/migration-core/tests/fixtures/change-column/', import.meta.url);
const load = filename => ({filename, source: readFileSync(new URL(filename, root), 'utf8')});
const first='2026_07_01_000000_create_users.php', second='2026_07_02_000000_change_users.php', third='2026_07_03_000000_reset_users.php';
const success=analyzeProject([third,second,first].map(load));
assert.equal(success.complete,true);
assert.equal(success.appliedCount,3);
assert.deepEqual(success.finalSchema.tables.users.columns.name,{name:'name',type:'string',length:50,nullable:false});
assert.equal(success.migrations[1].schemaAfter.tables.users.columns.at.useCurrent,true);
assert.equal(Object.hasOwn(success.finalSchema.tables.users.columns.at,'useCurrent'),false);
assert.equal(success.finalSchema.tables.users.indexes.users_name_unique.type,'unique');
assert.deepEqual(success.migrations[1].analysis.operations.map(o=>o.kind),['changeColumn','changeColumn']);
assert.deepEqual(success.migrations[1].diff.changes.map(c=>c.kind),['columnChanged','columnChanged']);
const blocked=analyzeProject([third,'2026_07_02_000000_missing.php',first].map(load));
assert.equal(blocked.finalSchema,null);
assert.equal(blocked.appliedCount,1);
assert.equal(Object.hasOwn(blocked.lastValidSchema.tables.users.columns,'partial'),false);
assert.equal(blocked.migrations[2].schemaBefore,null);
console.log(JSON.stringify({complete:success.complete,appliedCount:success.appliedCount,columns:success.finalSchema.tables.users.columns,blockedStatuses:blocked.migrations.map(m=>m.status)},null,2));
