import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { analyzeProject } from '@lmv/migration-core';
const root = new URL('../packages/migration-core/tests/fixtures/rename-index/', import.meta.url);
const file = filename => ({filename,source:readFileSync(new URL(filename,root),'utf8')});
const first='2026_09_01_000000_create_users.php', second='2026_09_02_000000_rename_users.php', third='2026_09_03_000000_drop_users_index.php';
const success=analyzeProject([third,second,first].map(file));
assert.equal(success.complete,true);
assert.equal(success.appliedCount,3);
assert.deepEqual(success.migrations[1].analysis.operations.map(o=>o.kind),['renameIndex']);
assert.deepEqual(success.migrations[1].schemaAfter.tables.users.indexes.new,{name:'new',type:'unique',columns:['b','a']});
assert.equal(Object.hasOwn(success.migrations[1].schemaAfter.tables.users.indexes,'old'),false);
assert.deepEqual(success.migrations[1].diff.changes.map(c=>c.kind),['indexAdded','indexRemoved']);
assert.deepEqual(success.finalSchema.tables.users.indexes,{});
const blocked=analyzeProject([third,'2026_09_02_000000_bad_users.php',first].map(file));
assert.equal(blocked.finalSchema,null);
assert.equal(blocked.appliedCount,1);
assert.deepEqual(Object.keys(blocked.lastValidSchema.tables.users.indexes),['old']);
assert.equal(blocked.migrations[2].schemaBefore,null);
console.log(JSON.stringify({appliedCount:success.appliedCount,renamedIndex:success.migrations[1].schemaAfter.tables.users.indexes.new,blockedStatuses:blocked.migrations.map(m=>m.status)},null,2));
