"""R7 optional Chromium task regression. Start Vite; requires environment Playwright."""
import json
import os
from pathlib import Path
from playwright.sync_api import sync_playwright, expect
base=os.environ.get('LMV_TEST_URL','http://127.0.0.1:5202')
checks=[]
with sync_playwright() as p:
 browser=p.chromium.launch(executable_path='/usr/bin/chromium',headless=True,args=['--no-sandbox'])
 page=browser.new_page(viewport={'width':1440,'height':1000})
 errors=[]
 page.on('console',lambda msg:errors.append(msg.text) if msg.type in ['error','warning'] else None)
 page.on('pageerror',lambda error:errors.append(str(error)))
 def load(name):
  page.get_by_role('button',name=name,exact=True).click()
  page.get_by_role('button',name='分析專案',exact=True).click()
  expect(page.get_by_label('Migration 閱讀工作區',exact=True)).to_be_visible()
 def select(index):
  page.locator('.reading-workspace .migration-list button').nth(index).click()
 def control(name): return page.locator('.workspace-controls').get_by_role('button',name=name,exact=True)
 def details(): return page.locator('.workspace-details')
 def header(): return page.locator('.workspace-controls')
 page.goto(base)
 load('載入成功範例')
 assert header().inner_text().startswith('專案最終 Schema')
 assert page.locator('[aria-label="Schema 快照檢視"] select').count()==0
 checks.append('final entry and fixed controls replace long primary selector')
 select(1)
 expect(header()).to_contain_text('第 2／3 份')
 node=page.get_by_role('button',name='選取或移動資料表 users',exact=True)
 node.click()
 expect(details()).to_contain_text('目前表：users')
 assert details().locator('details').first.evaluate('(e)=>e.open')
 assert 'nickname · string' in details().inner_text()
 control('下一份 migration').click()
 expect(header()).to_contain_text('第 3／3 份')
 expect(details()).to_contain_text('目前表：users')
 assert 'nickname · string' not in details().inner_text()
 assert control('下一份 migration').is_disabled()
 checks.append('click selects fixed details and next step preserves table with own metadata')
 control('套用前').click()
 assert 'nickname · string' in details().inner_text()
 control('前後比較').click()
 assert page.locator('.schema-graph').count()==2
 before=details().locator('section[aria-label="套用前資料表明細"]')
 after=details().locator('section[aria-label="套用後資料表明細"]')
 assert 'nickname · string' in before.inner_text() and 'nickname · string' not in after.inner_text()
 checks.append('comparison details use separate sides and removed column only before')
 control('套用後').click()
 page.locator('#result-query').fill('create_users')
 expect(header()).to_contain_text('目前閱讀步驟不在篩選清單')
 expect(header()).to_contain_text('第 3／3 份')
 control('前一份 migration').click()
 expect(header()).to_contain_text('第 2／3 份')
 page.locator('#result-query').fill('')
 checks.append('filter retains reading point and previous uses complete core order')
 # Select a source whose migration differs from the currently displayed step.
 origin=details().locator('[aria-label="操作來源 users"] button').first.element_handle()
 original_header=header().inner_text()
 original_graph=page.locator('.erd-canvas > g').get_attribute('transform')
 origin.click()
 expect(page.get_by_label('結構操作原始碼',exact=True)).to_be_visible()
 assert header().inner_text()==original_header
 assert 'create_users' in page.get_by_label('結構操作原始碼',exact=True).inner_text()
 details().locator('.table-inspector details').evaluate('(e)=>e.open=false')
 page.get_by_role('button',name='返回原結構選取',exact=True).click()
 assert origin.is_visible() and origin.evaluate('(e)=>e===document.activeElement')
 assert header().inner_text()==original_header
 assert page.locator('.erd-canvas > g').get_attribute('transform')==original_graph
 checks.append('other-migration preview and collapsed return preserve step/side/table/focus')
 # Keyboard selects a graph table; movement must not masquerade as selection.
 node=page.get_by_role('button',name='選取或移動資料表 users',exact=True)
 node.focus();node.press('Space')
 expect(details()).to_contain_text('目前表：users')
 node.focus();node.press('Enter')
 transform=node.get_attribute('transform')
 node.focus();node.press('ArrowRight')
 assert node.get_attribute('transform')!=transform
 checks.append('Space/Enter select and arrow key moves graph node')
 control('初始結構').click()
 expect(details()).to_contain_text('此快照沒有資料表 users')
 control('最終結構').click()
 expect(details()).to_contain_text('查看 users 的欄位')
 checks.append('initial/final entry retains literal selection without substituting tables')
 load('載入資料表生命週期範例')
 select(0)
 users=page.get_by_role('button',name='選取或移動資料表 users',exact=True)
 users.click()
 # Drag a different node; the current selected table must remain unchanged.
 articles=page.get_by_role('button',name='選取或移動資料表 posts',exact=True)
 page.get_by_role('button',name='重設 ERD 位置',exact=True).click()
 articles.scroll_into_view_if_needed()
 box=articles.bounding_box(); old=articles.get_attribute('transform')
 page.mouse.move(box['x']+20,box['y']+20);page.mouse.down();page.mouse.move(box['x']+65,box['y']+40,steps=8);page.mouse.up()
 assert articles.get_attribute('transform')!=old
 expect(details()).to_contain_text('目前表：users')
 checks.append('drag changes position without selecting another table')
 control('下一份 migration').click()
 expect(details()).to_contain_text('目前表：users')
 expect(details()).to_contain_text('此快照沒有資料表 users')
 control('套用前').click()
 expect(details()).to_contain_text('查看 users 的欄位')
 checks.append('rename preserves old literal query and absent side is explicit')
 load('載入失敗範例');select(0)
 page.get_by_role('button',name='選取或移動資料表 users',exact=True).click()
 select(1)
 expect(header()).to_contain_text('失敗')
 expect(details()).to_contain_text('此側快照未知')
 control('套用前').click();expect(details()).to_contain_text('查看 users 的欄位')
 control('下一份 migration').click()
 expect(header()).to_contain_text('已阻擋');expect(details()).to_contain_text('此側快照未知')
 control('最終結構').click();assert page.locator('.schema-graph').count()==0
 page.locator('.project-results > .diagnostics').get_by_role('button').first.click()
 expect(page.get_by_label('診斷原始碼定位',exact=True)).to_be_visible()
 expect(header()).to_contain_text('第 2／3 份')
 checks.append('diagnostic locate synchronizes failed step and retains source panel')
 checks.append('failed/blocked traversal and unknown final never use successful prefix')
 load('載入成功範例');select(1);control('套用後').click()
 page.get_by_label('搜尋目前快照欄位',exact=True).fill('display_name')
 page.get_by_role('button',name='查看欄位 users.display_name',exact=True).click()
 expect(details().locator('.column-detail[data-selected=true]')).to_contain_text('display_name')
 page.get_by_role('button',name='查看欄位 users.display_name',exact=True).click()
 expect(details().locator('.column-detail[data-selected=true]')).to_contain_text('display_name')
 # Summary jump and own-side column absence in comparison.
 obj=page.locator('.migration-reading li').filter(has=page.locator('strong',has_text='users.display_name'))
 obj.get_by_role('button',name='After · 查看明細',exact=True).click()
 expect(details().locator('.column-detail[data-selected=true]')).to_contain_text('display_name')
 control('前後比較').click()
 page.get_by_label('搜尋目前快照欄位',exact=True).nth(1).fill('display_name')
 page.get_by_role('button',name='查看欄位 users.display_name',exact=True).click()
 expect(details().locator('section[aria-label="套用前資料表明細"]')).to_contain_text('沒有欄位 display_name')
 expect(details().locator('section[aria-label="套用後資料表明細"] .column-detail[data-selected=true]')).to_contain_text('display_name')
 control('套用後').click()
 checks.append('column search/reselection and summary jump share fixed details; comparison reads own columns')
 page.set_viewport_size({'width':390,'height':844})
 control('下一份 migration').click();expect(header()).to_contain_text('第 3／3 份')
 expect(details()).to_contain_text('目前表：users')
 origin=details().locator('[aria-label="操作來源 users"] button').first.element_handle();origin.click()
 page.get_by_role('button',name='返回原結構選取',exact=True).click()
 assert origin.evaluate('(e)=>e===document.activeElement')
 assert page.evaluate('document.documentElement.scrollWidth <= window.innerWidth')
 Path('artifacts').mkdir(exist_ok=True)
 page.screenshot(path='artifacts/r7-workspace-narrow.png',full_page=True)
 checks.append('390px reading and source return without horizontal overflow')
 page.set_viewport_size({'width':1440,'height':1000})
 header().scroll_into_view_if_needed();page.screenshot(path='artifacts/r7-workspace.png')
 # Editing a browser copy invalidates the entire result/workspace.
 page.locator('#project-source').fill(page.locator('#project-source').input_value()+'\n// copy changed')
 expect(page.locator('.reading-workspace')).to_have_count(0)
 checks.append('input edit invalidates workspace and source')
 # Fixed R1 copies: no parser expansion and no unknown-final substitution.
 for sample,count,applied,failed in [('laravelio',9,2,2),('bookstack',103,0,0)]:
  paths=sorted(Path('artifacts/research-inputs',sample,'database/migrations').glob('*.php'))
  assert len(paths)==count
  page.locator('#migration-files').set_input_files([str(path.resolve()) for path in paths])
  page.get_by_role('button',name='分析專案',exact=True).click()
  expect(header()).to_contain_text('專案最終 Schema')
  assert page.locator('.schema-graph').count()==0
  select(failed)
  expect(header()).to_contain_text('失敗')
  expect(details()).to_contain_text('此側快照未知')
  control('套用前').click()
  if applied:
   page.get_by_role('button',name='選取或移動資料表 jobs',exact=True).click()
   expect(details()).to_contain_text('目前表：jobs')
  else:
   expect(page.locator('.workspace-center')).to_contain_text('沒有資料表')
  control('下一份 migration').click()
  expect(header()).to_contain_text('已阻擋')
  expect(details()).to_contain_text('此側快照未知')
  checks.append(f'{sample}: {count} original files retain failed/blocked and unknown final')
 assert not errors,errors
 browser.close()
report={'passed':checks,'consoleErrors':errors}
Path('artifacts/r7-browser.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(report,ensure_ascii=False,indent=2))
